// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// clearsky_cpp
Rcpp::NumericVector clearsky_cpp(Rcpp::NumericVector zen_deg, double temp_C, double relhum, double pres_hPa);
RcppExport SEXP _terravars_clearsky_cpp(SEXP zen_degSEXP, SEXP temp_CSEXP, SEXP relhumSEXP, SEXP pres_hPaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type zen_deg(zen_degSEXP);
    Rcpp::traits::input_parameter< double >::type temp_C(temp_CSEXP);
    Rcpp::traits::input_parameter< double >::type relhum(relhumSEXP);
    Rcpp::traits::input_parameter< double >::type pres_hPa(pres_hPaSEXP);
    rcpp_result_gen = Rcpp::wrap(clearsky_cpp(zen_deg, temp_C, relhum, pres_hPa));
    return rcpp_result_gen;
END_RCPP
}
// annual_solar_weights_cpp
Rcpp::NumericMatrix annual_solar_weights_cpp(double lat, double lon, int year, double temp_C, double relhum, double pres_hPa, double dt_h);
RcppExport SEXP _terravars_annual_solar_weights_cpp(SEXP latSEXP, SEXP lonSEXP, SEXP yearSEXP, SEXP temp_CSEXP, SEXP relhumSEXP, SEXP pres_hPaSEXP, SEXP dt_hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< int >::type year(yearSEXP);
    Rcpp::traits::input_parameter< double >::type temp_C(temp_CSEXP);
    Rcpp::traits::input_parameter< double >::type relhum(relhumSEXP);
    Rcpp::traits::input_parameter< double >::type pres_hPa(pres_hPaSEXP);
    Rcpp::traits::input_parameter< double >::type dt_h(dt_hSEXP);
    rcpp_result_gen = Rcpp::wrap(annual_solar_weights_cpp(lat, lon, year, temp_C, relhum, pres_hPa, dt_h));
    return rcpp_result_gen;
END_RCPP
}
// solar_index_cpp
Rcpp::NumericMatrix solar_index_cpp(Rcpp::NumericMatrix slope, Rcpp::NumericMatrix aspect, double solar_zenith, double solar_azimuth, Rcpp::NumericMatrix horizon);
RcppExport SEXP _terravars_solar_index_cpp(SEXP slopeSEXP, SEXP aspectSEXP, SEXP solar_zenithSEXP, SEXP solar_azimuthSEXP, SEXP horizonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type aspect(aspectSEXP);
    Rcpp::traits::input_parameter< double >::type solar_zenith(solar_zenithSEXP);
    Rcpp::traits::input_parameter< double >::type solar_azimuth(solar_azimuthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type horizon(horizonSEXP);
    rcpp_result_gen = Rcpp::wrap(solar_index_cpp(slope, aspect, solar_zenith, solar_azimuth, horizon));
    return rcpp_result_gen;
END_RCPP
}
// solar_index_tme_cpp
Rcpp::NumericMatrix solar_index_tme_cpp(Rcpp::NumericMatrix slope, Rcpp::NumericMatrix aspect, Rcpp::NumericMatrix lat, Rcpp::NumericMatrix lon, Rcpp::IntegerVector years, Rcpp::IntegerVector months, Rcpp::IntegerVector days, Rcpp::NumericVector hours, Rcpp::NumericVector horizon_cube, double az_step);
RcppExport SEXP _terravars_solar_index_tme_cpp(SEXP slopeSEXP, SEXP aspectSEXP, SEXP latSEXP, SEXP lonSEXP, SEXP yearsSEXP, SEXP monthsSEXP, SEXP daysSEXP, SEXP hoursSEXP, SEXP horizon_cubeSEXP, SEXP az_stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type aspect(aspectSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lat(latSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type years(yearsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type months(monthsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type days(daysSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hours(hoursSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type horizon_cube(horizon_cubeSEXP);
    Rcpp::traits::input_parameter< double >::type az_step(az_stepSEXP);
    rcpp_result_gen = Rcpp::wrap(solar_index_tme_cpp(slope, aspect, lat, lon, years, months, days, hours, horizon_cube, az_step));
    return rcpp_result_gen;
END_RCPP
}
// solar_pos_cpp
Rcpp::NumericMatrix solar_pos_cpp(double lat, double lon, Rcpp::IntegerVector years, Rcpp::IntegerVector months, Rcpp::IntegerVector days, Rcpp::NumericVector hours);
RcppExport SEXP _terravars_solar_pos_cpp(SEXP latSEXP, SEXP lonSEXP, SEXP yearsSEXP, SEXP monthsSEXP, SEXP daysSEXP, SEXP hoursSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type years(yearsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type months(monthsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type days(daysSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hours(hoursSEXP);
    rcpp_result_gen = Rcpp::wrap(solar_pos_cpp(lat, lon, years, months, days, hours));
    return rcpp_result_gen;
END_RCPP
}
// horizon_angle_cpp
Rcpp::NumericMatrix horizon_angle_cpp(Rcpp::NumericMatrix elev, double res, double azimuth, int n_steps, double obs_hgt);
RcppExport SEXP _terravars_horizon_angle_cpp(SEXP elevSEXP, SEXP resSEXP, SEXP azimuthSEXP, SEXP n_stepsSEXP, SEXP obs_hgtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type elev(elevSEXP);
    Rcpp::traits::input_parameter< double >::type res(resSEXP);
    Rcpp::traits::input_parameter< double >::type azimuth(azimuthSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< double >::type obs_hgt(obs_hgtSEXP);
    rcpp_result_gen = Rcpp::wrap(horizon_angle_cpp(elev, res, azimuth, n_steps, obs_hgt));
    return rcpp_result_gen;
END_RCPP
}
// sky_view_factor_cpp
Rcpp::NumericMatrix sky_view_factor_cpp(Rcpp::NumericVector horizon_cube);
RcppExport SEXP _terravars_sky_view_factor_cpp(SEXP horizon_cubeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type horizon_cube(horizon_cubeSEXP);
    rcpp_result_gen = Rcpp::wrap(sky_view_factor_cpp(horizon_cube));
    return rcpp_result_gen;
END_RCPP
}
// twostream_tme_cpp
Rcpp::List twostream_tme_cpp(Rcpp::NumericMatrix slope, Rcpp::NumericMatrix aspect, Rcpp::NumericMatrix pai, Rcpp::NumericMatrix lref, Rcpp::NumericMatrix ltra, Rcpp::NumericMatrix xmat, Rcpp::NumericMatrix gref, Rcpp::NumericMatrix lat, Rcpp::NumericMatrix lon, Rcpp::IntegerVector years, Rcpp::IntegerVector months, Rcpp::IntegerVector days, Rcpp::NumericVector hours, bool pai_horiz);
RcppExport SEXP _terravars_twostream_tme_cpp(SEXP slopeSEXP, SEXP aspectSEXP, SEXP paiSEXP, SEXP lrefSEXP, SEXP ltraSEXP, SEXP xmatSEXP, SEXP grefSEXP, SEXP latSEXP, SEXP lonSEXP, SEXP yearsSEXP, SEXP monthsSEXP, SEXP daysSEXP, SEXP hoursSEXP, SEXP pai_horizSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type aspect(aspectSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lref(lrefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type ltra(ltraSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xmat(xmatSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gref(grefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lat(latSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type years(yearsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type months(monthsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type days(daysSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type hours(hoursSEXP);
    Rcpp::traits::input_parameter< bool >::type pai_horiz(pai_horizSEXP);
    rcpp_result_gen = Rcpp::wrap(twostream_tme_cpp(slope, aspect, pai, lref, ltra, xmat, gref, lat, lon, years, months, days, hours, pai_horiz));
    return rcpp_result_gen;
END_RCPP
}
// canopy_diffuse_frac_cpp
Rcpp::NumericMatrix canopy_diffuse_frac_cpp(Rcpp::NumericMatrix pai, Rcpp::NumericMatrix lref, Rcpp::NumericMatrix ltra, Rcpp::NumericMatrix xmat, Rcpp::NumericMatrix gref);
RcppExport SEXP _terravars_canopy_diffuse_frac_cpp(SEXP paiSEXP, SEXP lrefSEXP, SEXP ltraSEXP, SEXP xmatSEXP, SEXP grefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lref(lrefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type ltra(ltraSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xmat(xmatSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gref(grefSEXP);
    rcpp_result_gen = Rcpp::wrap(canopy_diffuse_frac_cpp(pai, lref, ltra, xmat, gref));
    return rcpp_result_gen;
END_RCPP
}
// veg_path_atten_cpp
Rcpp::NumericMatrix veg_path_atten_cpp(Rcpp::NumericMatrix elev, Rcpp::NumericMatrix hgt, Rcpp::NumericMatrix pai, Rcpp::NumericMatrix xmat, double res, double zenith, double azimuth, int n_steps);
RcppExport SEXP _terravars_veg_path_atten_cpp(SEXP elevSEXP, SEXP hgtSEXP, SEXP paiSEXP, SEXP xmatSEXP, SEXP resSEXP, SEXP zenithSEXP, SEXP azimuthSEXP, SEXP n_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type elev(elevSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type hgt(hgtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xmat(xmatSEXP);
    Rcpp::traits::input_parameter< double >::type res(resSEXP);
    Rcpp::traits::input_parameter< double >::type zenith(zenithSEXP);
    Rcpp::traits::input_parameter< double >::type azimuth(azimuthSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(veg_path_atten_cpp(elev, hgt, pai, xmat, res, zenith, azimuth, n_steps));
    return rcpp_result_gen;
END_RCPP
}
// veg_path_diffuse_cpp
Rcpp::NumericMatrix veg_path_diffuse_cpp(Rcpp::NumericMatrix elev, Rcpp::NumericMatrix hgt, Rcpp::NumericMatrix pai, Rcpp::NumericMatrix lref, Rcpp::NumericMatrix ltra, double res, double zenith, double azimuth, int n_steps);
RcppExport SEXP _terravars_veg_path_diffuse_cpp(SEXP elevSEXP, SEXP hgtSEXP, SEXP paiSEXP, SEXP lrefSEXP, SEXP ltraSEXP, SEXP resSEXP, SEXP zenithSEXP, SEXP azimuthSEXP, SEXP n_stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type elev(elevSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type hgt(hgtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pai(paiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lref(lrefSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type ltra(ltraSEXP);
    Rcpp::traits::input_parameter< double >::type res(resSEXP);
    Rcpp::traits::input_parameter< double >::type zenith(zenithSEXP);
    Rcpp::traits::input_parameter< double >::type azimuth(azimuthSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(veg_path_diffuse_cpp(elev, hgt, pai, lref, ltra, res, zenith, azimuth, n_steps));
    return rcpp_result_gen;
END_RCPP
}
// twi_cpp
Rcpp::NumericMatrix twi_cpp(Rcpp::NumericMatrix flow_acc, Rcpp::NumericMatrix slope_deg, double res, std::string method, double min_slope);
RcppExport SEXP _terravars_twi_cpp(SEXP flow_accSEXP, SEXP slope_degSEXP, SEXP resSEXP, SEXP methodSEXP, SEXP min_slopeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type flow_acc(flow_accSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type slope_deg(slope_degSEXP);
    Rcpp::traits::input_parameter< double >::type res(resSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type min_slope(min_slopeSEXP);
    rcpp_result_gen = Rcpp::wrap(twi_cpp(flow_acc, slope_deg, res, method, min_slope));
    return rcpp_result_gen;
END_RCPP
}
// basinCpp
IntegerMatrix basinCpp(NumericMatrix& dm2, IntegerMatrix& bsn, std::string method);
RcppExport SEXP _terravars_basinCpp(SEXP dm2SEXP, SEXP bsnSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type dm2(dm2SEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type bsn(bsnSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(basinCpp(dm2, bsn, method));
    return rcpp_result_gen;
END_RCPP
}
// basinmerge_cpp
IntegerMatrix basinmerge_cpp(NumericMatrix& dm2, IntegerMatrix& bm2, double boundary);
RcppExport SEXP _terravars_basinmerge_cpp(SEXP dm2SEXP, SEXP bm2SEXP, SEXP boundarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type dm2(dm2SEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type bm2(bm2SEXP);
    Rcpp::traits::input_parameter< double >::type boundary(boundarySEXP);
    rcpp_result_gen = Rcpp::wrap(basinmerge_cpp(dm2, bm2, boundary));
    return rcpp_result_gen;
END_RCPP
}
// fillsinks_cpp
NumericMatrix fillsinks_cpp(NumericMatrix& dm2, NumericMatrix& wseed2);
RcppExport SEXP _terravars_fillsinks_cpp(SEXP dm2SEXP, SEXP wseed2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type dm2(dm2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type wseed2(wseed2SEXP);
    rcpp_result_gen = Rcpp::wrap(fillsinks_cpp(dm2, wseed2));
    return rcpp_result_gen;
END_RCPP
}
// flowacc_cpp
NumericMatrix flowacc_cpp(NumericMatrix& dm2, NumericMatrix& wt2, IntegerMatrix& bm2, int method);
RcppExport SEXP _terravars_flowacc_cpp(SEXP dm2SEXP, SEXP wt2SEXP, SEXP bm2SEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type dm2(dm2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type wt2(wt2SEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type bm2(bm2SEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(flowacc_cpp(dm2, wt2, bm2, method));
    return rcpp_result_gen;
END_RCPP
}
// flowpath_cpp
IntegerMatrix flowpath_cpp(NumericMatrix& dm, IntegerVector src_rows, IntegerVector src_cols, bool d8);
RcppExport SEXP _terravars_flowpath_cpp(SEXP dmSEXP, SEXP src_rowsSEXP, SEXP src_colsSEXP, SEXP d8SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_rows(src_rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_cols(src_colsSEXP);
    Rcpp::traits::input_parameter< bool >::type d8(d8SEXP);
    rcpp_result_gen = Rcpp::wrap(flowpath_cpp(dm, src_rows, src_cols, d8));
    return rcpp_result_gen;
END_RCPP
}
// flowpath_mfd_cpp
NumericMatrix flowpath_mfd_cpp(NumericMatrix& dm, IntegerVector src_rows, IntegerVector src_cols, bool d8);
RcppExport SEXP _terravars_flowpath_mfd_cpp(SEXP dmSEXP, SEXP src_rowsSEXP, SEXP src_colsSEXP, SEXP d8SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_rows(src_rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_cols(src_colsSEXP);
    Rcpp::traits::input_parameter< bool >::type d8(d8SEXP);
    rcpp_result_gen = Rcpp::wrap(flowpath_mfd_cpp(dm, src_rows, src_cols, d8));
    return rcpp_result_gen;
END_RCPP
}
// flowpath_up_cpp
IntegerMatrix flowpath_up_cpp(NumericMatrix& dm, IntegerVector src_rows, IntegerVector src_cols, bool d8);
RcppExport SEXP _terravars_flowpath_up_cpp(SEXP dmSEXP, SEXP src_rowsSEXP, SEXP src_colsSEXP, SEXP d8SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_rows(src_rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_cols(src_colsSEXP);
    Rcpp::traits::input_parameter< bool >::type d8(d8SEXP);
    rcpp_result_gen = Rcpp::wrap(flowpath_up_cpp(dm, src_rows, src_cols, d8));
    return rcpp_result_gen;
END_RCPP
}
// flowpath_mfd_up_cpp
NumericMatrix flowpath_mfd_up_cpp(NumericMatrix& dm, IntegerVector src_rows, IntegerVector src_cols, bool d8);
RcppExport SEXP _terravars_flowpath_mfd_up_cpp(SEXP dmSEXP, SEXP src_rowsSEXP, SEXP src_colsSEXP, SEXP d8SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_rows(src_rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type src_cols(src_colsSEXP);
    Rcpp::traits::input_parameter< bool >::type d8(d8SEXP);
    rcpp_result_gen = Rcpp::wrap(flowpath_mfd_up_cpp(dm, src_rows, src_cols, d8));
    return rcpp_result_gen;
END_RCPP
}
// coastal_exposure_cpp
Rcpp::NumericMatrix coastal_exposure_cpp(Rcpp::NumericMatrix lsm, double resolution, double xmin, double ymax, Rcpp::NumericVector s, double direction, Rcpp::List masks, Rcpp::NumericVector mask_reso, Rcpp::NumericVector mask_xmin, Rcpp::NumericVector mask_xmax, Rcpp::NumericVector mask_ymin, Rcpp::NumericVector mask_ymax, double jitter_deg);
RcppExport SEXP _terravars_coastal_exposure_cpp(SEXP lsmSEXP, SEXP resolutionSEXP, SEXP xminSEXP, SEXP ymaxSEXP, SEXP sSEXP, SEXP directionSEXP, SEXP masksSEXP, SEXP mask_resoSEXP, SEXP mask_xminSEXP, SEXP mask_xmaxSEXP, SEXP mask_yminSEXP, SEXP mask_ymaxSEXP, SEXP jitter_degSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type lsm(lsmSEXP);
    Rcpp::traits::input_parameter< double >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type direction(directionSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type masks(masksSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mask_reso(mask_resoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mask_xmin(mask_xminSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mask_xmax(mask_xmaxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mask_ymin(mask_yminSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mask_ymax(mask_ymaxSEXP);
    Rcpp::traits::input_parameter< double >::type jitter_deg(jitter_degSEXP);
    rcpp_result_gen = Rcpp::wrap(coastal_exposure_cpp(lsm, resolution, xmin, ymax, s, direction, masks, mask_reso, mask_xmin, mask_xmax, mask_ymin, mask_ymax, jitter_deg));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_terravars_clearsky_cpp", (DL_FUNC) &_terravars_clearsky_cpp, 4},
    {"_terravars_annual_solar_weights_cpp", (DL_FUNC) &_terravars_annual_solar_weights_cpp, 7},
    {"_terravars_solar_index_cpp", (DL_FUNC) &_terravars_solar_index_cpp, 5},
    {"_terravars_solar_index_tme_cpp", (DL_FUNC) &_terravars_solar_index_tme_cpp, 10},
    {"_terravars_solar_pos_cpp", (DL_FUNC) &_terravars_solar_pos_cpp, 6},
    {"_terravars_horizon_angle_cpp", (DL_FUNC) &_terravars_horizon_angle_cpp, 5},
    {"_terravars_sky_view_factor_cpp", (DL_FUNC) &_terravars_sky_view_factor_cpp, 1},
    {"_terravars_twostream_tme_cpp", (DL_FUNC) &_terravars_twostream_tme_cpp, 14},
    {"_terravars_canopy_diffuse_frac_cpp", (DL_FUNC) &_terravars_canopy_diffuse_frac_cpp, 5},
    {"_terravars_veg_path_atten_cpp", (DL_FUNC) &_terravars_veg_path_atten_cpp, 8},
    {"_terravars_veg_path_diffuse_cpp", (DL_FUNC) &_terravars_veg_path_diffuse_cpp, 9},
    {"_terravars_twi_cpp", (DL_FUNC) &_terravars_twi_cpp, 5},
    {"_terravars_basinCpp", (DL_FUNC) &_terravars_basinCpp, 3},
    {"_terravars_basinmerge_cpp", (DL_FUNC) &_terravars_basinmerge_cpp, 3},
    {"_terravars_fillsinks_cpp", (DL_FUNC) &_terravars_fillsinks_cpp, 2},
    {"_terravars_flowacc_cpp", (DL_FUNC) &_terravars_flowacc_cpp, 4},
    {"_terravars_flowpath_cpp", (DL_FUNC) &_terravars_flowpath_cpp, 4},
    {"_terravars_flowpath_mfd_cpp", (DL_FUNC) &_terravars_flowpath_mfd_cpp, 4},
    {"_terravars_flowpath_up_cpp", (DL_FUNC) &_terravars_flowpath_up_cpp, 4},
    {"_terravars_flowpath_mfd_up_cpp", (DL_FUNC) &_terravars_flowpath_mfd_up_cpp, 4},
    {"_terravars_coastal_exposure_cpp", (DL_FUNC) &_terravars_coastal_exposure_cpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_terravars(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
