# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clearsky_cpp <- function(zen_deg, temp_C = 15.0, relhum = 60.0, pres_hPa = 1013.25) {
    .Call(`_terravars_clearsky_cpp`, zen_deg, temp_C, relhum, pres_hPa)
}

annual_solar_weights_cpp <- function(lat, lon, year = 2023L, temp_C = 15.0, relhum = 60.0, pres_hPa = 1013.25, dt_h = 0.5) {
    .Call(`_terravars_annual_solar_weights_cpp`, lat, lon, year, temp_C, relhum, pres_hPa, dt_h)
}

solar_index_cpp <- function(slope, aspect, solar_zenith, solar_azimuth, horizon) {
    .Call(`_terravars_solar_index_cpp`, slope, aspect, solar_zenith, solar_azimuth, horizon)
}

solar_index_tme_cpp <- function(slope, aspect, lat, lon, years, months, days, hours, horizon_cube, az_step) {
    .Call(`_terravars_solar_index_tme_cpp`, slope, aspect, lat, lon, years, months, days, hours, horizon_cube, az_step)
}

solar_pos_cpp <- function(lat, lon, years, months, days, hours) {
    .Call(`_terravars_solar_pos_cpp`, lat, lon, years, months, days, hours)
}

horizon_angle_cpp <- function(elev, res, azimuth, n_steps = 0L, obs_hgt = 0.0) {
    .Call(`_terravars_horizon_angle_cpp`, elev, res, azimuth, n_steps, obs_hgt)
}

sky_view_factor_cpp <- function(horizon_cube) {
    .Call(`_terravars_sky_view_factor_cpp`, horizon_cube)
}

twostream_tme_cpp <- function(slope, aspect, pai, lref, ltra, xmat, gref, lat, lon, years, months, days, hours, pai_horiz) {
    .Call(`_terravars_twostream_tme_cpp`, slope, aspect, pai, lref, ltra, xmat, gref, lat, lon, years, months, days, hours, pai_horiz)
}

canopy_diffuse_frac_cpp <- function(pai, lref, ltra, xmat, gref) {
    .Call(`_terravars_canopy_diffuse_frac_cpp`, pai, lref, ltra, xmat, gref)
}

veg_path_atten_cpp <- function(elev, hgt, pai, xmat, res, zenith, azimuth, n_steps = 0L) {
    .Call(`_terravars_veg_path_atten_cpp`, elev, hgt, pai, xmat, res, zenith, azimuth, n_steps)
}

veg_path_diffuse_cpp <- function(elev, hgt, pai, lref, ltra, res, zenith, azimuth, n_steps = 0L) {
    .Call(`_terravars_veg_path_diffuse_cpp`, elev, hgt, pai, lref, ltra, res, zenith, azimuth, n_steps)
}

twi_cpp <- function(flow_acc, slope_deg, res, method, min_slope) {
    .Call(`_terravars_twi_cpp`, flow_acc, slope_deg, res, method, min_slope)
}

basinCpp <- function(dm2, bsn, method) {
    .Call(`_terravars_basinCpp`, dm2, bsn, method)
}

basinmerge_cpp <- function(dm2, bm2, boundary) {
    .Call(`_terravars_basinmerge_cpp`, dm2, bm2, boundary)
}

fillsinks_cpp <- function(dm2, wseed2) {
    .Call(`_terravars_fillsinks_cpp`, dm2, wseed2)
}

flowacc_cpp <- function(dm2, wt2, bm2, method) {
    .Call(`_terravars_flowacc_cpp`, dm2, wt2, bm2, method)
}

coastal_exposure_cpp <- function(lsm, resolution, xmin, ymax, s, direction, masks, mask_reso, mask_xmin, mask_xmax, mask_ymin, mask_ymax, jitter_deg = 0.0) {
    .Call(`_terravars_coastal_exposure_cpp`, lsm, resolution, xmin, ymax, s, direction, masks, mask_reso, mask_xmin, mask_xmax, mask_ymin, mask_ymax, jitter_deg)
}

